//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIC.Bot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesDialog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesDialog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BIC.Bot.Resources.MessagesDialog", typeof(MessagesDialog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antes de poder hablar a tu casa por favor haz login.
        /// </summary>
        public static string AuthLoginRequired {
            get {
                return ResourceManager.GetString("AuthLoginRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autenticación realizada con éxito.
        /// </summary>
        public static string AuthLoginSucceded {
            get {
                return ResourceManager.GetString("AuthLoginSucceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persiana de la habitación bajada.
        /// </summary>
        public static string BlindDownBedroom {
            get {
                return ResourceManager.GetString("BlindDownBedroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persianas de la casa bajadas.
        /// </summary>
        public static string BlindDownHomeAll {
            get {
                return ResourceManager.GetString("BlindDownHomeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persiana de la cocina bajada.
        /// </summary>
        public static string BlindDownKitchen {
            get {
                return ResourceManager.GetString("BlindDownKitchen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persiana del buzón bajada.
        /// </summary>
        public static string BlindDownMailbox {
            get {
                return ResourceManager.GetString("BlindDownMailbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persiana de la habitación subida.
        /// </summary>
        public static string BlindUpBedroom {
            get {
                return ResourceManager.GetString("BlindUpBedroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas las persianas de la casa subidas.
        /// </summary>
        public static string BlindUpHomeAll {
            get {
                return ResourceManager.GetString("BlindUpHomeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persiana de la cocina subida.
        /// </summary>
        public static string BlindUpKitchen {
            get {
                return ResourceManager.GetString("BlindUpKitchen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persiana del correo subida.
        /// </summary>
        public static string BlindUpMailBox {
            get {
                return ResourceManager.GetString("BlindUpMailBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor facilítame un código de acceso creado desde tu app de autenticación.
        /// </summary>
        public static string DirectLineMessageLogin {
            get {
                return ResourceManager.GetString("DirectLineMessageLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hola buenas noches.
        /// </summary>
        public static string GreetingNight {
            get {
                return ResourceManager.GetString("GreetingNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hola buenas tardes.
        /// </summary>
        public static string GreetingsLater {
            get {
                return ResourceManager.GetString("GreetingsLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hola buenos días.
        /// </summary>
        public static string GreetingsMorning {
            get {
                return ResourceManager.GetString("GreetingsMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿En qué necesitas ayuda?.
        /// </summary>
        public static string HelpMessage {
            get {
                return ResourceManager.GetString("HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagada la luz del baño.
        /// </summary>
        public static string LightOffBathroomMessage {
            get {
                return ResourceManager.GetString("LightOffBathroomMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagada la luz del recibidor.
        /// </summary>
        public static string LightOffEntranceHallMessage {
            get {
                return ResourceManager.GetString("LightOffEntranceHallMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagadas todas las luces de la casa.
        /// </summary>
        public static string LightOffHomeMessage {
            get {
                return ResourceManager.GetString("LightOffHomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagada la luz de la cocina.
        /// </summary>
        public static string LightOffKitchenMessage {
            get {
                return ResourceManager.GetString("LightOffKitchenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enciendida la luz del baño.
        /// </summary>
        public static string LightOnBathroomMessage {
            get {
                return ResourceManager.GetString("LightOnBathroomMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enciendida la luz del recibidor.
        /// </summary>
        public static string LightOnEntranceHallMessage {
            get {
                return ResourceManager.GetString("LightOnEntranceHallMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encendidas todas las luces de la casa.
        /// </summary>
        public static string LightOnHomeMessage {
            get {
                return ResourceManager.GetString("LightOnHomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enciendida la luz de la cocina.
        /// </summary>
        public static string LightOnKitchenMessage {
            get {
                return ResourceManager.GetString("LightOnKitchenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagada la luz de la habitación.
        /// </summary>
        public static string LigthOffBedroomMessage {
            get {
                return ResourceManager.GetString("LigthOffBedroomMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enciendida la luz de la habitación.
        /// </summary>
        public static string LigthOnBedroomMessage {
            get {
                return ResourceManager.GetString("LigthOnBedroomMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Qué luz de la casa quieres apagar?.
        /// </summary>
        public static string LigthsOffMessage {
            get {
                return ResourceManager.GetString("LigthsOffMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Qué parte de la casa quieres encender?.
        /// </summary>
        public static string LIgthsOnMessage {
            get {
                return ResourceManager.GetString("LIgthsOnMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo siento Dave, me temo que no puedo hacer eso.
        /// </summary>
        public static string MessageHal9000 {
            get {
                return ResourceManager.GetString("MessageHal9000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta no es una opción válida.
        /// </summary>
        public static string PromptInvalidOptionMessage {
            get {
                return ResourceManager.GetString("PromptInvalidOptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acción no entendida. Ejemplo: encender luz cocina.
        /// </summary>
        public static string SmsActionNotUnderstanding {
            get {
                return ResourceManager.GetString("SmsActionNotUnderstanding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crea un código de acceso de tu App de autenticación.
        /// </summary>
        public static string SmsUserNotLogged {
            get {
                return ResourceManager.GetString("SmsUserNotLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No te entendí un carajo.
        /// </summary>
        public static string UserMessageNotUnderstanding {
            get {
                return ResourceManager.GetString("UserMessageNotUnderstanding", resourceCulture);
            }
        }
    }
}
